import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AgentResolver Connector Information",
  description:
    "Hosted MCP endpoint, access requirements, payment behavior, support, privacy, and terms for AgentResolver."
};

const prompts = [
  "Before I pay this x402 endpoint, verify the recipient, price, network, asset, and resource binding.",
  "Check whether this x402 payment request is within a $0.05 budget before I authorize it.",
  "Find a compatible API or MCP capability for this task and show me what still needs verification."
];

export default function ConnectorPage() {
  return (
    <main>
      <div className="eyebrow">CONNECTOR INFORMATION</div>
      <h1>AgentResolver hosted MCP connector.</h1>
      <p className="lead">
        AgentResolver is a non-custodial x402 payment verification service for
        autonomous agents, with free capability discovery and paid verification
        tools. This page collects the public integration facts a connector host
        or reviewer may need in one place.
      </p>

      <div className="grid">
        <section>
          <h2>Product + hosted MCP</h2>
          <p>
            Website: <a href="https://agentresolver.vercel.app">https://agentresolver.vercel.app</a>
          </p>
          <p>
            Endpoint: <code>https://agentresolver.vercel.app/mcp</code>
          </p>
          <p>
            Protocol: hosted Streamable HTTP MCP. No account, API key, or OAuth
            login is required to connect.
          </p>
        </section>

        <section>
          <h2>Access requirements</h2>
          <p>
            Free discovery and quote surfaces require no subscription. Paid
            tools require a caller that can authorize the displayed x402 USDC
            payment on a supported network. AgentResolver never receives the
            caller&apos;s private key.
          </p>
        </section>

        <section>
          <h2>Payments</h2>
          <p>
            The connector includes both free and paid tools. The canonical
            payment Guard is <strong>$0.001 USDC</strong> per successful check
            on Base or Solana where advertised. Paid tools disclose price,
            asset, network, and recipient before payment through HTTP 402.
          </p>
        </section>
      </div>

      <section>
        <h2>What people can ask the connector to do</h2>
        <ul>
          {prompts.map(prompt => (
            <li key={prompt}>{prompt}</li>
          ))}
        </ul>
      </section>

      <section>
        <h2>Authentication and authorization</h2>
        <p>
          AgentResolver does not use account authentication for the hosted MCP
          endpoint. Paid execution uses x402 payment authorization generated by
          the caller&apos;s own wallet after the service presents a 402 payment
          challenge. A successful AgentResolver result is evidence for the
          caller&apos;s policy; it is not permission from AgentResolver to spend.
        </p>
      </section>

      <section>
        <h2>Public review links</h2>
        <p>
          <a href="/docs">Documentation</a> ·{" "}
          <a href="/mcp/server-card">MCP server card</a> ·{" "}
          <a href="/openapi.json">OpenAPI</a> ·{" "}
          <a href="/privacy">Privacy policy</a> ·{" "}
          <a href="/terms">Terms of service</a> ·{" "}
          <a href="/support">Support</a>
        </p>
      </section>

      <section>
        <h2>Developer and support</h2>
        <p>
          Developer: Wade Wickingson. Support:{" "}
          <a href="mailto:waxsway@gmail.com">waxsway@gmail.com</a>.
        </p>
      </section>

      <p className="links">
        <a href="/">Home</a> · <a href="/docs">Docs</a> ·{" "}
        <a href="/legal">Legal &amp; Safety</a>
      </p>
    </main>
  );
}
